# Generated by Django 3.2.5 on 2021-08-02 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.DateField(blank=True)),
                ('from_hour', models.TimeField(blank=True)),
                ('to_hour', models.TimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient', models.CharField(help_text='Patient Name', max_length=100)),
                ('office', models.CharField(help_text='number office', max_length=3, null=True)),
                ('day_of_appointment', models.DateField()),
                ('time_of_appointment', models.TimeField()),
                ('status', models.CharField(choices=[('o', 'On'), ('p', 'planned'), ('c', 'complete')], default='p', max_length=1)),
                ('date_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='time_table.timetable')),
            ],
            options={
                'ordering': ['time_of_appointment'],
            },
        ),
    ]
